services:
  - type: web
    name: stock-dashboard-api
    env: node
    plan: free
    autoDeploy: false
    buildCommand: cd server && npm install
    startCommand: cd server && node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
